version: '3'
services:

  server:
    entrypoint:
        node build/index
    build:
      context: server
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
    - mongodb
    environment:
      - mongoDomain=mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017